### ISSUE TITLE
(javadoc) `@JsonFormat` does not use `TimeZone.getDefault()`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-annotations#106]
Javadocs for `@JsonFormat` should not claim that the default timezone is used, as UTC is used by default.

**Comment by shmosel** [comment]
Why does it still say it it defaults to the "system default"?

**Comment by cowtowncoder** [comment]
@shmosel What says?

**Comment by shmosel** [comment]
The Javadocs...

**Comment by cowtowncoder** [comment]
@shmosel  Existing javadocs for older branches are not republished, although javadocs bundled are created to match released code.

**Comment by shmosel** [comment]
I'm talking about the updated version.
