### ISSUE TITLE
JsonFormat.Feature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS deserialization analogue

### ISSUE THREAD

**Issue by henryptung** [FasterXML/jackson-annotations#118]
Version: All

JsonFormat.Feature offers a limited set of available/configurable features, but in particular it only offers the serialization half of `WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS`. This is almost certainly going to be wrong, because configuring only serialization means that deserialization will likely not match, and round-trip serializability will be lost.

**Comment by cowtowncoder** [comment]
@henryptung Not necessarily so; it depends entirely on exactly how serialization works. If actual shapes vary (for example, inclusion of nanoseconds done using array; or floating-point vs integer), deserializer can support all styles without limit.

**Comment by henryptung** [comment]
@cowtowncoder Fair enough; but for the standard Java 8 time implementation, I think the default behavior breaks (as the deserialization will interpret the `seconds.nanoseconds` value as epoch millis + discarded fraction.

**Comment by cowtowncoder** [comment]
@henryptung Are you sure? I thought jsr-310 module specifically uses floating-point number (or perhaps array) to make distinction explicit. Joda does not (I think) support nano-second resolution.

**Comment by cowtowncoder** [comment]
I think that this needs to be handled in bit different way, using `@JsonFormat` or something similar. JSR-310 module has some issues related, and bigger suggestions are collected under JSTEP-5:

https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-5

Closing this particular issue (it'd belong under jackson-databind tracker)
