### ISSUE TITLE
“jackson”  There are a lot of shortcomings in this product！

### ISSUE THREAD

**Issue by thousmile** [FasterXML/jackson-annotations#128]
Unable to parse recursive objects!  A mistake has happened
![qq 20180113183338](https://user-images.githubusercontent.com/28520524/34905337-99ce925a-f891-11e7-8993-d8853f596e08.jpg)

My entity class is like this！
![qq 20180113184508](https://user-images.githubusercontent.com/28520524/34905356-e991a638-f891-11e7-9fde-e037e4871fa2.jpg)

Other products can be parsed normally，
For example, Alibaba fastJson，
![qq 20180113183823](https://user-images.githubusercontent.com/28520524/34905383-5dde73a4-f892-11e7-8ef3-55fb497eeb3d.jpg)

I hope you can update it, too。

Thank you ！

**Comment by cowtowncoder** [comment]
I do not understand what you are trying to say here. But for usage questions please use mailing list:

https://groups.google.com/group/jackson-user/

and not issue tracker. Issue tracker is for reporting flaws, not question about how to use features.
