### ISSUE TITLE
@JsonView

### ISSUE THREAD

**Issue by pstree** [FasterXML/jackson-annotations#131]
```
@JsonView(include={A.class,B.class} ，exclude={C.class})
@JsonView(include={A.class,B.class})
@JsonView(exclude={C.class})
```

**Comment by cowtowncoder** [comment]
Please elaborate on what you are suggesting. I think I can guess but I'd prefer explicit explanation.

**Comment by pstree** [comment]
Yes, I'm sorry . It seems that I should learn more English.  I have an entity and a paging. I want to dynamically exclude a lazy loaded @ManyToOne
