### ISSUE TITLE
FEATURE:@JsonOnlyProperties / @JsonIncludeProperties needed

### ISSUE THREAD

**Issue by sunphy** [FasterXML/jackson-annotations#133]
Let's say you have 1 entity with cascade need to be serialized, when you only need serialize  part of cascaded entity, you should do it as following:
```
class Organization{
    private int id;
    private String name;
    private String address;
    private String telehpone;
    private String website;
    ......
}
```

```
class Person{
    private int id;
    private String firstName;
    private String lastName;
    @JsonIgnoreProperties({"address","telephone","website"})
    private Organization organization;
}
```

but what if the ignored properties is too many and I only need the id and name properties to be serialized?A `@JsonOnlyProperties` or `@JsonIncludeProperties` is more convenient and very easy to use.
Think this scenario is most needed.

**Comment by cowtowncoder** [comment]
I think this is already filed as:

https://github.com/FasterXML/jackson-databind/issues/1296

and the reason it sort of belongs more in `jackson-databind` is just because adding annotation is simple, but adding actual handling and support is anything but (due to complexity of processing, at this point).

**Comment by sunphy** [comment]
OK.Thank you.
I think this is very useful!

**Comment by cowtowncoder** [comment]
Closing this in favor of the issue mentioned above.

**Comment by sp4ce** [comment]
Pull request:
 - https://github.com/FasterXML/jackson-annotations/pull/174
 - https://github.com/FasterXML/jackson-databind/pull/2771
