### ISSUE TITLE
Add `JsonFormat.Feature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-annotations#134]
There is already `DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT`, but that is global setting. Would be good to have per-property counterpart.

**Comment by cowtowncoder** [comment]
Hmmh. With 2.12 there is the new `CoercionConfigs` set up:

https://github.com/FasterXML/jackson-databind/issues/2113

which will cover (some of?) the use case(s); but also would make this feature more difficult to implement. So unless that feature proves to have significant gaps (it has much wider applicability, so should cover more cases in general, but sometimes there are still also gaps), will close this issue.

**Comment by ddaaac** [comment]
So, is there any feature to set `ACCEPT_EMPTY_STRING_AS_NULL_OBJECT` per-class?
I tried to use `CoercionAction.AS_NULL`, but i don't know how to use it.
