### ISSUE TITLE
JsonFormat.Feature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT but for composite types

### ISSUE THREAD

**Issue by paroxysm** [FasterXML/jackson-annotations#135]
Hey guy,
So awhile ago an issue was fixed with the mapper de-serializing empty string types such as `<first/>` into a null, as opposed to a "".

There's also a similar issue affected composite types as well.
Consider pseudo-xsd:
```
<complexType name="Parent">
  <element name="child" type="Child" maxOccurs="0"/>
</complexType>

<complexType name="Child">
 <element name="member1"/>
 <element name="member2"/>
 <element name="member3"/>
...
</complexType>
```

If maven-jaxb-plugin generate POJOs for this, I get pseudo-java:
```
class Parent {  List<Child> child }
class Child { ... }
```

If I try to deserialize:

`<Parent/>`

I'll end up with a null object.
However, one would expect to end up with a non-null instance of "Parent", that has an empty or null list of "Child"

**Comment by cowtowncoder** [comment]
This sounds like an XML issue, so needs to be filed at `jackson-dataformat-xml`. This repository only contains annotation definitions, and not code that uses them for configuration.

As to issue itself: Jackson does not use XML Schema for anything, so its inclusion does not help a lot. But full class definition (relevant parts), including annotations, is needed, as well as code for reading/writing content.

**Comment by paroxysm** [comment]
Ah, understood.
