### ISSUE TITLE
@JsonCreator Javadoc's "see alson" points to itself.

### ISSUE THREAD

**Issue by brunoabdon** [FasterXML/jackson-annotations#136]
`@JsonCreator`'s Javadoc points to itself in the "See Also" section.

https://github.com/FasterXML/jackson-annotations/blob/c3dbf7913d1c7ee4c3bd70fcb11408bb1deaf5ca/src/main/java/com/fasterxml/jackson/annotation/JsonCreator.java#L41

**Comment by cowtowncoder** [comment]
That's not very good. :)
Thank you for reporting this.
