### ISSUE TITLE
Add Automatic-Module-Name for JDK9 interoperability

### ISSUE THREAD

**Issue by forax** [FasterXML/jackson-annotations#138]
Hi,
https://github.com/FasterXML/jackson-core/issues/397 add Automatic-Module-Name to core and databind but other projects like jackson-annotations were not updated.

Stephen Colebourne has started to list all projects that have a list an Automatic-Module-Name, as you can see only core and databind have been updated
https://github.com/jodastephen/jpms-module-names/blob/master/generated/module-maven.properties#L1

I personally need jackson-annotations and  jackson-module-java8 so i will log a bug for these two modules but all modules should be updated IMO.

**Comment by cowtowncoder** [comment]
Checkout 2.9 branch: Automatic-Name is included. Unfortunately change was not in for 2.9.0, so in this rare instances, `2.9.1` or later should be used as dependency. Need to think of whether `jackson-bom` should reflect this.

Will work as expected for 2.10 at least.

**Comment by forax** [comment]
ok thanks,
i will test that soon
