### ISSUE TITLE
question: inner string field to a object?

### ISSUE THREAD

**Issue by gMan1990** [FasterXML/jackson-annotations#144]
how: from ```{"desc":"{\"a\":1}"}``` to History instance(```{"desc":{"a":1}}```) ?
same question: https://stackoverflow.com/questions/43118435/jackson-parse-string-field-as-json

```
public Class History{

 // what annotation here?
 private Desc desc;
 //get, set method

 public Class Desc{
  private int a;
  //get, set method
 }

}
```

**Comment by cowtowncoder** [comment]
This is an issue tracker, not discussion forum. But if I understand question correctly, no, there is no automated way of doing "json in json". You could do `setDesc(String str)` in which you parse contents, however. Or assign custom deserializer for class `Desc`, or field "desc" (use `@JsonDeserialize(using = MyDeserializer.class)`).

Hope this helps.
