### ISSUE TITLE
@JsonFormat(pattern="yyyy-MM-dd") allows 2018-11-29ufdudfufs

### ISSUE THREAD

**Issue by ShubhamRohatgi** [FasterXML/jackson-annotations#146]
I am using the @JsonFormat to valid the date format. 

Annotation used:- 
@JsonFormat(pattern = "yyyy-MM-dd", lenient = OptBoolean.FALSE)

It is working fine with correct value example (2018-11-29) and also throwing an error with bad value (2018-31-11). But if the correct value is appended with the characters or special characters (2018-11-29ufdudfufs$$$) , it is not throwing any error.

Let me know if I am using the mentioned annotation wrongly.

**Comment by cowtowncoder** [comment]
I'd like to see a unit test reproduction: this could be considered a bug.
Also: although annotation is defined here, issue needs to go in `jackson-databind` (if value is of `java.util.Date` or `Calendar`), since that's where actual parsing is handled.

**Comment by cowtowncoder** [comment]
May be refiled at `jackson-databind`, along with reproduction.
