### ISSUE TITLE
How to Provide default operation on a field

### ISSUE THREAD

**Issue by Rishabhadept** [FasterXML/jackson-annotations#155]
I want to provide a default operation on a numeric field. 

For eg: I  have an integer field called "price" and I want to always multiply the value of this field by 100.
So even if someone assigns a value to it. While using getter we should always get the result as ="value*100".

Is there any annotation available for this type of operation?

**Comment by cowtowncoder** [comment]
In future please use mailing list

https://groups.google.com/forum/#!forum/jackson-user

for asking questions.

But no, Jackson does not add support for code injection or general purpose value transformations.
So you'd have to implement that in method, or use something like AOP library/tools to do it.
