### ISSUE TITLE
Please include 2.9.1 version as dependency for other 2.9.* modules

### ISSUE THREAD

**Issue by remal** [FasterXML/jackson-annotations#157]
Currently all Jackson Maven modules depends on `com.fasterxml.jackson.core:jackson-annotations:2.9.0`. This version doesn't have `Automatic-Module-Name` in `META-INF/MANIFEST.MF`.

From version 2.9.1 all Jackson Maven modules has `Automatic-Module-Name` in `META-INF/MANIFEST.MF`. So, please, use at least 2.9.1 version of `com.fasterxml.jackson.core:jackson-annotations` as a dependency for all modules (for example, jackson-databind, jackson-bom, ...)

**Comment by cowtowncoder** [comment]
This could be done for `2.9.10`; I'll have to think about it a bit.

**Comment by cowtowncoder** [comment]
Since 2.10 and 2.11 have been released, and there is unlikely to be another full 2.9 patch release (just micro-patches), I think I will close this.
