### ISSUE TITLE
Please turn annotations into a module that is not an autogenerated one

### ISSUE THREAD

**Issue by denismakogon** [FasterXML/jackson-annotations#158]
I'm attempting to refactor an application to a modular one.
However, with Jackson, it's not easy enough due to the inability to build a jlink-ed runtime.
```
[ERROR] Error: automatic module cannot be used with jlink: com.fasterxml.jackson.annotation
```
dependency version is: `2.9.9`

**Comment by cowtowncoder** [comment]
I am not sure if I understand this correctly, but Jackson 2.10 does add full `module-info`.
It would be helpful if you could try out the first pre-release candidate, 2.10.0.pr1, and see if that works better. We are hoping to get some help from users to validate this as I do not run on JDK 11 yet, so any validation I can do is bit superficial.

**Comment by denismakogon** [comment]
Can confirm, 2.10 works as you said. Thank you.

**Comment by GedMarc** [comment]
Confirmed Windows 11->13

**Comment by cowtowncoder** [comment]
@denismakogon Thank you for verifying (and ditto @GedMarc for extensive checking above and beyond)
