### ISSUE TITLE
Checksum mismatches for jackson-annotations-2.10.0.pom in Maven Central

### ISSUE THREAD

**Issue by tazle** [FasterXML/jackson-annotations#161]
Locally calculated checksums for https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.pom do not match the checksum files https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.pom.md5 and https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.pom.sha1.

```
$ curl 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.pom' 2> /dev/null | md5sum
e2c027469445bed5f64692678dc3a939  -
$ curl -q 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.pom.md5'
b7ac7889cdb51d9287360b0356cf2c52
```

```
$ curl 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.pom' 2> /dev/null | sha1sum
9eaf096e9f2b4ed7d5f866b09b5121f6eb85963a  -
$ curl -q 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.pom.sha1'
bd4d05e97ec9dc0a5494412055df8f36bc8dbc27
```

**Comment by tazle** [comment]
The signature also seems to be off:
```
$ gpg --verify jackson-annotations-2.10.0.pom.asc jackson-annotations-2.10.0.pom
gpg: Signature made Fri 27 Sep 2019 05:16:14 EEST
gpg:                using RSA key 6214760097DC5CFAD0175AC2C9FBAA83A8753994
gpg: BAD signature from "Tatu Saloranta (cowtowncoder) <tatu.saloranta@iki.fi>" [unknown]
```

**Comment by renatocaval** [comment]
I just run into this issue as well. Seems that there were some problems when publishing to Maven Central and some artefacts were uploaded manually. Probably some mismatching.

see also https://groups.google.com/forum/#!topic/jackson-announce/szKKqRvDhzg

**Comment by kupci** [comment]
There's also an issue opened with Sonatype here; https://issues.sonatype.org/browse/OSSRH-51881

**Comment by cowtowncoder** [comment]
Yes, please comment on above-mentioned issue: unfortunately there is not much I can do directly, but Sonatype admins are aware of the issue and help to resolve it.
