### ISSUE TITLE
How do I parse json in an unusual format like({name:jake})?

### ISSUE THREAD

**Issue by monday110** [FasterXML/jackson-annotations#170]
when I post a json in Header without utf-8 forexample(Content-Type：application/json) {“name”:"jack"}
after zuul get the json body ({name:jack}),with @valid shrow exception.

**Comment by cowtowncoder** [comment]
For usage questions please use one of following resources:

* User group: https://groups.google.com/forum/#!forum/jackson-user
* Gitter chat: https://gitter.im/FasterXML/jackson-databind
