### ISSUE TITLE
Document that @JsonAlias can be used on enum values

### ISSUE THREAD

**Issue by mjustin** [FasterXML/jackson-annotations#193]
https://github.com/FasterXML/jackson-databind/issues/2352 added support for using `@JsonAlias` to accept alternate enum values.  However, this functionality is not documented in the [`@JsonAlias` Javadocs](http://fasterxml.github.io/jackson-annotations/javadoc/2.13/com/fasterxml/jackson/annotation/JsonValue.html).  It was therefore quite the surprise to me to discover this was a valid usage.

I believe the Javadocs should be updated to document this case.

Examples in other annotations that change enum values in addition to a separate primary usage:

[`@JsonValue`](http://fasterxml.github.io/jackson-annotations/javadoc/2.13/com/fasterxml/jackson/annotation/JsonValue.html):

> NOTE: when use for Java `enum`s, one additional feature is that value returned by annotated method is also considered to be the value to deserialize from, not just JSON String to serialize as. This is possible since set of Enum values is constant and it is possible to define mapping, but can not be done in general for POJO types; as such, this is not used for POJO deserialization.

[`@JsonProperty`](http://fasterxml.github.io/jackson-annotations/javadoc/2.13/com/fasterxml/jackson/annotation/JsonProperty.html):

> Starting with Jackson 2.6 this annotation may also be used to change serialization of `Enum` like so:
>
> ```java
> public enum MyEnum {
>      @JsonProperty("theFirstValue") THE_FIRST_VALUE,
>      @JsonProperty("another_value") ANOTHER_VALUE;
> }
> ```
> as an alternative to using [`JsonValue`](http://fasterxml.github.io/jackson-annotations/javadoc/2.13/com/fasterxml/jackson/annotation/JsonValue.html) annotation.

**Comment by mukham12** [comment]
Hi @cowtowncoder,

Can this be closed now that the requested change is merged?

**Comment by cowtowncoder** [comment]
Yes, will close thank you @mukham12 !
