### ISSUE TITLE
enable @jsonignores  ignore property of property of and more...

### ISSUE THREAD

**Issue by gitsupi** [FasterXML/jackson-annotations#196]
suppose we have Product Object it has 
```
 
Attribute["attributeValues"]
->
AttributeValue["products"]
->
Product["seller"]
->
Seller["shops"]
->
Shop["attributes"]
->
Attribute["attributeValues"]
->
AttributeValue["products"]
->
Product["seller"]
 
Seller["shops"]
->
Shop["attributes"]
->
Attribute["attributeValues"]  
```

we need something like 

` @JsonIgnoreProperties(value = {"products","shops['products'],"S['X[""Z]']""})`

**Comment by cowtowncoder** [comment]
No, Jackson does not support such nested configuration.

You can add `@JsonIgnoreProperties` on fields, however, to do some of what you want.
But it does and will not support general path expressions.
