### ISSUE TITLE
@JsonIgnore usage instead of @JsonManagedReference and @JsonBackReference

### ISSUE THREAD

**Issue by ramazansakin** [FasterXML/jackson-annotations#197]
Hi,
I used @JsonManagedReference and @JsonBackReference first on my entities like:

![image](https://user-images.githubusercontent.com/9968219/152672407-1f57cb77-c0a8-45bc-abfa-cda641538184.png)

and 

![image](https://user-images.githubusercontent.com/9968219/152672413-48029c92-3084-4240-9e6f-7ce2981b027f.png)

and then when I try to add new airport, I got : 
![image](https://user-images.githubusercontent.com/9968219/152672435-5c254f79-082a-42dd-8d67-7612fa94df3d.png)

But when I try to switch the references, it worked properly. Also, when I add @JsonIgnore annotation any of entity, it also worked properly. From all above, what is the purpose of exact usage of  @JsonManagedReference and @JsonBackReference ?

Thanks

**Comment by cowtowncoder** [comment]
For usage question, please use either mailing lists:

* https://groups.google.com/g/jackson-user

or git chatter:

* https://gitter.im/FasterXML/jackson-databind

Second: your question seems to be through another framework (and annotations) which may change handling. It would probably be necessary to try to use annotations and read/write with only Jackson annotations to isolate the issue.
Or maybe reach to to Spring users' help forums first.
