### ISSUE TITLE
Add @Inherited annotation to all Jackson annotations

### ISSUE THREAD

**Issue by emmersonbonnat-tw** [FasterXML/jackson-annotations#198]
We migrated to Micronaut 3.3.3 from 2.x recently and since Micronaut 3.0 there is a [breaking change](https://docs.micronaut.io/3.0.0/guide/#breaks) in Annotation Inheritance. Due to this the Jackson annotations that are not annotated with @java.lang.annotation.Inherited are not inherited from parent classes and interfaces.

Can you add @Inherited annotation to all Jackson annotations.

**Comment by emmersonbonnat-tw** [comment]
Closing this to create under jackson-databind

**Comment by cowtowncoder** [comment]
Actually this might have been a better place. But it's fine, there are annotations in both.
