### ISSUE TITLE
`@JsonIgnore` on `public boolean isSomething()` methods: Bug or feature ?

### ISSUE THREAD

**Issue by dili91** [FasterXML/jackson-annotations#200]
Hey, I'm posting here a question as I could not find an active `jackson-users` group on Google groups - Might be due to my lack of familiarity with the tool. In that case, sorry for that! 

Today, I noticed an unexpected (or at least it is to me) behavior while using the `@JacksonIgnore` annotation on a `public boolean isSomething()` method. Let me get straight to the point with a basic example: 

I have this `AccountIdentifier` class: 
```
public class AccountIdentifier {
  private String iban;

  private final String type = "iban";

  public AccountIdentifier(String iban){
      this.iban = iban;
  }

  public String getIban() {
      return iban;
  }
  public String getType() {
      return type;
  }

  public boolean isIban(){
      return true;
  }
}
```

If I create an instance of this class and serialize it to a `String`, everything work as expected: below assertion is ✅ 

```
AccountIdentifier accountIdentifier = new AccountIdentifier("12345678");

Assertions.assertEquals("{\"iban\":\"12345678\",\"type\":\"iban\"}", objectMapper.writeValueAsString(accountIdentifier))
```

Where objectMapper is configured like this: 
```
ObjectMapper objectMapper = new ObjectMapper();

// required for optionals deserialization
objectMapper.registerModule(new Jdk8Module());
// serialize all camel cases fields to snake
objectMapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE);
// do not include null fields in JSON
objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
// do not fail in case of unknown properties returned JSON payloads
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

That said, I wanted to highlight the fact that the `isIban()` method should not produce any output while deserializing, so I put a `@JsonIgnore` annotation on top of it: 
```
@JsonIgnore
public boolean isIban(){
    return true;
}
```

But after doing so the above test started failing bc the `iban` property was missing in the serialized object ❌ 
```
expected: <{"iban":"12345678","type":"iban"}> but was: <{"type":"iban"}>

```

Is this behaviour expected ? 
I would have expected no changes in the test output. 

PS: I would have expected the above to happen if the type of `iban` was boolean.

Thanks! 
Ciao

**Comment by cowtowncoder** [comment]
It'd be "jackson-user" -- https://groups.google.com/g/jackson-user -- or can try gitter https://gitter.im/FasterXML/jackson-databind.

As to this case: not that both `isIban()` and `getIban()` are valid accessors; but if you only add one annotation on either one of them, it'll have an effect; particularly `@JsonIgnore`.
If you want to indicate "use this, not that", you need to add `@JsonProperty` on one to keep, `@JsonIgnore` on one to ignore. This is the case for getters vs setters as well: the common use case being one where user wants to use minimum number of annotations. So if there is a disagreement (want to keep setter, not getter f.ex), add separate annotations.

HTH.

**Comment by dili91** [comment]
Hey @cowtowncoder, thanks for explaining the rationale behind it. Makes sense.

I tried the following and my test is happy again: 
```
public class AccountIdentifier {
  @JsonProperty
  private String iban;

  private final String type = "iban";

  public AccountIdentifier(String iban){
      this.iban = iban;
  }

  public String getIban() {
      return iban;
  }
  public String getType() {
      return type;
  }

  @JsonIgnore
  public boolean isIban(){
      return true;
  }
}
```
Do you think it's worth highlighting this behavior a bit more on the documentation? Either in the README of this repo or in the Javadoc?

Regarding this one: 
> It'd be "jackson-user" -- https://groups.google.com/g/jackson-user -- or can try gitter https://gitter.im/FasterXML/jackson-databind.

There was a broken link in the issue template, I raised #201 to fix that. 

Thank you !

**Comment by cowtowncoder** [comment]
Yes this could be an improvement. Note, too, that you could have placed `@JsonProperty` on `getIban()`; that's a matter of taste.

Thank you for reporting #201!

**Comment by dili91** [comment]
> Yes this could be an improvement. Note, too, that you could have placed `@JsonProperty` on `getIban()`; that's a matter of taste.
> 
> Thank you for reporting #201!

Cool! Though my entity is also used for deserialization so I **think** I would need that on the setter as well. Anyway clear, I'm closing this issue
