### ISSUE TITLE
Allow explicit `JsonSubTypes` repeated names check

### ISSUE THREAD

**Issue by ancane** [FasterXML/jackson-annotations#204]
Hi) Got a project at hand, using tons of JsonSubTypes with logical short names defined for the brevity of serialized data. Usually, it's pretty hard to manually check there are no repeated name/names aliases defined when adding a new subtype. I would like to explicitly state and validate there are no repeated subtype names defined. Please, consider related PR for this matter and suggest the best way to do this if PR is not good enough. I Will also PR the databind repo with the implementation of the check. Also please advise, how to add this to the 2.12 branch if that's at all possible. Cheers!

**Comment by cowtowncoder** [comment]
Was implemented via https://github.com/FasterXML/jackson-databind/issues/3500
