### ISSUE TITLE
Why @JsonProperty annotation can be ignored?

### ISSUE THREAD

**Issue by shabanovve** [FasterXML/jackson-annotations#23]
I use annotation with "crnId" field in a class like this:

@JsonProperty("internalid")
private Long crmId;

But I see 
{"action":"updateCustomer","data":{"firstname":"au043","lastname":"au043","email":"au043@mail.ru"},"crmId":186} 
after serialization in JSON string.
It seems that annotation has been ignored.
How it can be fixed?

**Comment by derrylvarghese** [comment]
@cowtowncoder  - I am having the same problem as mentioned here. Here is my SO question with sample app. http://stackoverflow.com/questions/40169084/jsonproperty-not-working-weblogic-12-2-1-and-java-8
