### ISSUE TITLE
Extracting Mixin infrastructure to a general purpose library

### ISSUE THREAD

**Issue by ittaiz** [FasterXML/jackson-annotations#51]
hi,
I might be wrong here but I think that it might be interesting to have the mixin infrastructure as a general purpose library.
In my company we have something that adds metadata on exceptions for client communications, monitoring and BI. This works with annotations and I think adding mixin support can be interesting.
Seeing as I like this feature in Jackson I thought to try and see if you think it can be generalized.

**Comment by cowtowncoder** [comment]
Actually, Classmate library:

https://github.com/cowtowncoder/java-classmate

has basics of mix-in processing, in addition to type resolution. I wrote it starting with Jackson's type resolution and mix-in functionality, so in a way it is a superset.

**Comment by ittaiz** [comment]
looks very interesting.
I'll continue searching there.
Thanks!
