### ISSUE TITLE
How to deserialize to arraylist

### ISSUE THREAD

**Issue by ppamorim** [FasterXML/jackson-annotations#54]
I need deserialize a string(json) to a arraylist<model> inside a model. Anyone can help me?

**Comment by cowtowncoder** [comment]
Google for "issue tracker", and its purpose. It is not a general question support forum.

**Comment by ppamorim** [comment]
Github has a label "Question", and yes it's a challenge and this should be documented. It's the basic for a library so used...

**Comment by ppamorim** [comment]
Solved! For help more educated people , unlike many here ...

On first model:

    @JsonProperty("property")
    @JsonDeserialize(as=ArrayList.class, contentAs=ModelTwo.class)
      private List<ModelTwo> modelsTwo;

On second model:

    @JsonCreator
      public ModelTwo(
          @JsonProperty("id") int id,
          @JsonProperty("name") String name) {
        this.id = id;
        this.name = name;
      }

**Comment by cowtowncoder** [comment]
Ah. I was not aware of such a type. I hope there is a way to remove this, because this is not a good forum for asking questions. I am glad you found a solution to your problem.
