### ISSUE TITLE
Does Jackson have versioning support - similar to GSON's @Since(1.0)

### ISSUE THREAD

**Issue by rajeshkamal** [FasterXML/jackson-annotations#57]
Does Jackson have this kind of a feature. This would be really helpful in implementing REST API's versioning support.

https://sites.google.com/site/gson/gson-user-guide#TOC-Versioning-Support

https://code.google.com/p/google-gson/source/browse/trunk/gson/src/main/java/com/google/gson/annotations/Since.java

**Comment by cowtowncoder** [comment]
Not directly, although `@JsonView` offers something that could be used to approximate it.

But please use mailing lists and discussions groups for questions. This is issue tracker.
