### ISSUE TITLE
@JsonRootName Not Working for Collection Type

### ISSUE THREAD

**Issue by haribachala** [FasterXML/jackson-annotations#63]
The following is the test case.

------------------
POJO Classs
-----------------

@JsonRootName("Employee")
public class Employee implements Serializable {
     private String empName;
     private String empNo;
     public String getEmpName() {
          return empName;
     }
  public void setEmpName(String empName) {
          this.empName = empName;
     }
     public String getEmpNo() {
          return empNo;
     }
     public void setEmpNo(String empNo) {
          this.empNo = empNo;
     }
}

-----------------
TEST CASE
------------------
public class EmployeeTest {
    @Test
    public void testEMPJsonData() throws  Exception{

        Employee emp =new Employee();
        emp.setEmpName("john");
        emp.setEmpNo("1234");
        emp.setPermentAddress("india");
        List<Employee> empList = new ArrayList<Employee>();
        empList.add(emp);
        /********** - JACKSON *******************/
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(MapperFeature.USE_WRAPPER_NAME_AS_PROPERTY_NAME, true);
        mapper.configure(SerializationFeature.WRAP_ROOT_VALUE, true);
        mapper.setAnnotationIntrospector(new AnnotationIntrospectorPair(new  JacksonAnnotationIntrospector(), new JaxbAnnotationIntrospector(TypeFactory.defaultInstance())));
        mapper.writeValue(System.out, empList); 
 
    }
}

----------------
ouput
----------------
{"ArrayList":[{"empName":"john","empNo":"1234"}]}

Expected : {"Employee":[{"empName":"john","empNo":"1234"}]}

why it behaving like this for collections?

**Comment by cowtowncoder** [comment]
Actually belongs to https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/44 as per original (or under `jackson-databind`), as this module only defines annotations, but no handling.
