### ISSUE TITLE
@JsonCreator javadoc should mention @JsonValue

### ISSUE THREAD

**Issue by Raniz85** [FasterXML/jackson-annotations#68]
These two go hand in hand and the documentation for `@JsonValue` mentions `@JsonCreator`, but the documentation for `@JsonCreator` doesn't mention `@JsonValue` at all.

Should make it a bit easier to find it if you stumble upon `@JsonCreator` first (as I did).

**Comment by cowtowncoder** [comment]
Makes sense, I can add a reference.

**Comment by cowtowncoder** [comment]
Improved javadocs a bit; since we only publish javadocs on minor releases, most likely will be part of 2.7.
