### ISSUE TITLE
Typo in Javadoc

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-annotations#69]
http://fasterxml.github.io/jackson-annotations/javadoc/2.2.0/com/fasterxml/jackson/annotation/JsonBackReference.html reads `Logical have for the reference property pair`

The phrase "logical have" does not make sense. Is this a typo?

**Comment by cowtowncoder** [comment]
Possibly. I do not modify or re-publish old javadocs, so that'll probably remain as is. If same is still in place for latest version(s) that may be fixed.
