### ISSUE TITLE
JsonFormat date not working

### ISSUE THREAD

**Issue by marccollin** [FasterXML/jackson-annotations#71]
I use spring-boot, spring-rest, spring-jpa-data. 
In my database (mysql), i have date field. 

example: 2015-09-29.

I would like to display like with this format: "dd/MM/yyyy".

In my DTO, i do

```java
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", timezone="EST")
private Date birthdate;
```
on web side, i receive 2015-09-29 not 09/29/2015

**Comment by cowtowncoder** [comment]
I would need a stand-alone unit test for this, not including Spring components. Also, which Jackson version is this with?

**Comment by marccollin** [comment]
2.5.4

**Comment by cowtowncoder** [comment]
2.5 should have support for format patterns for `java.util.Date`, so that should be ok.
But I can not reproduce issue without a unit test.

**Comment by cowtowncoder** [comment]
Can not reproduce. But if this can be demonstrated with a unit test, should be reported against `jackson-databind`, as annotations project only defines annotation types but does not implement handling.
