### ISSUE TITLE
JsonInclude.Include.NON_EMPTY awkward docs

### ISSUE THREAD

**Issue by jayanderson** [FasterXML/jackson-annotations#72]
The current paragraph:

> Value that indicates that only properties that have values
> that values that are null or what is considered empty are
> not to be included.

I think what's meant is:

> Value that indicates that properties with values
> that are null or are considered empty will not be included.

Or

> Properties with null or empty values will not be included
> when using this value.

Or something similar. This is a very minor issue I just had a hard time parsing the paragraph at first.

**Comment by cowtowncoder** [comment]
Thanks! Fixed for 2.7 as suggested. Also improved javadoc further along similar lines.
