### ISSUE TITLE
Empty JSON object does not trigger deserialization

### ISSUE THREAD

**Issue by debel** [FasterXML/jackson-annotations#74]
Hi, 
I have an POST endpoint accepting a specific class as body. The class has a property marked with `@JSONProperty(required=true)`

However when I pass an empty JSON object to the endpoint no error is triggered. If I put an irrelevant property e.q. `{"qwerty": 1234}` I get an exception.

Is it a bug, or am I doing something wrong?

Thanks in advance :)

p.s. I am running with jackson 3.0.9.Final

**Comment by cowtowncoder** [comment]
This is a question best suited for mailing list, so please use those in future.

But I think what you are finding is that currently `required` property is only used as metadata for things like JSON Schema generation; existence of values for such properties is not support for properties.
Except for one case: when using `@JsonCreator`, existence of these properties is actually validated, as of Jackson 2.6 (I assume 3.0.9 refers to some other framework like Spring perhaps?).
