### ISSUE TITLE
Error at open link from README

### ISSUE THREAD

**Issue by Cunhazera** [FasterXML/jackson-annotations#86]
When I try to open the link from `Databind package` at the README [it](https://github.com/FasterXML/jackson-annotations/blob/master/FasterXML/jackson-databind) returns 404.

Supposed it to be [this link](https://github.com/FasterXML/jackson-databind) ?

**Comment by cowtowncoder** [comment]
Thanks, fixed.

**Comment by Cunhazera** [comment]
Great!
