### ISSUE TITLE
Dead documentation link

### ISSUE THREAD

**Issue by idkw** [FasterXML/jackson-annotations#97]
Hi,

I want to learn more about Jackson Mixins but the link given in the wiki is dead.

The link http://wiki.fasterxml.com/JacksonMixInAnnotations is dead on this page : 
https://github.com/FasterXML/jackson-annotations/wiki/Mixin-Annotations

Is there a complete documentation about mixins somewhere else ? 
I've only found small example like here : http://demeranville.com/writing-csv-using-jackson-csvmapper-mixin-annotations/

Thanks

**Comment by cowtowncoder** [comment]
I'll try to get wiki system to restart -- I don't have access myself but know who does.

In the meantime, maybe this:

http://www.cowtowncoder.com/blog/archives/2009/08/entry_305.html

helps? Idea itself is simple, and any and all Jackson annotations can be associated with a target class using mix-in approach. So it's not something that only supports certain annotations.
